-- PARTE 1

CREATE TABLESPACE mid_term 
DATAFILE 'MID_TERM.dbf' SIZE 50 M
ONLINE;

CREATE USER MOLAYA
IDENTIFIED BY MOLAYA
QUOTA UNLIMITED ON mid_term;

-- ROL #1
CREATE PROFILE MINI_DBA 

GRANT CREATE TABLES TO MINI_DBA ;
GRANT CREATE SEQUENCE  TO MINI_DBA ;

-- ROL #2
CREATE PROFILE STUDENT

GRANT CONNECT TO STUDENT;
GRANT CREATE SESSION TO STUDENT ;



-- PARTE 2
CREATE SEQUENCE MUNICIPIOS_SEQ 
MINVALUE 1 MAXVALUE 100
START WITH 10 
INCREMENT BY 1 
NOCYCLE;

CREATE SEQUENCE CAPTURAS_SEQ 
MINVALUE 1 MAXVALUE 6000 
START WITH 5000
INCREMENT BY 1 
NOCYCLE;

-- TABLAS 

CREATE TABLE MUNICIPIOS (

	ID INTEGER PRIMARY KEY,
    NOMBRE VARCHAR2(255)
);

CREATE TABLE CAPTURAS(
    
    ID INTEGER PRIMARY KEY,
    FECHA INTEGER,
    DEPARTAMENTO VARCHAR2(255),
    MUNICIPIO_ID VARCHAR2(255),
    DIA INTEGER ,
    BARRIO VARCHAR2(255),
    ZONA VARCHAR2(255),
    CLASE_SITIO VARCHAR2(255),
    EDAD INTEGER ,
    SEXO VARCHAR2(255),
    ESTADO CIVIL VARCHAR2(255),
    CLASE_EMPLEADO VARCHAR2(255),
    PROFESION VARCHAR2(255),
    ESCOLARIDAD VARCHAR2(255),
    DELITO VARCHAR2(255)
);

ALTER TABLE CAPTURAS ADD CONSTRAINT MUNICIPIO_FK FOREIGN KEY(MUNICIPIO_ID) REFERENCES MUNICIPIOS(ID);
